// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SocialMediaManager.API.Data;

#nullable disable

namespace SocialMediaManager.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("SocialMediaManager.API.Models.DiscordAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DiscordId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TokenExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("DiscordAccounts");
                });

            modelBuilder.Entity("SocialMediaManager.API.Models.ScheduledPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PlatformAccountId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("PostedTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ScheduledTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("scheduled");

                    b.Property<string>("TargetId")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ScheduledPosts");
                });

            modelBuilder.Entity("SocialMediaManager.API.Models.TelegramAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BotToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TelegramId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("TelegramAccounts");
                });

            modelBuilder.Entity("SocialMediaManager.API.Models.TwitterAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TokenExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("TwitterId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("TwitterAccounts");
                });

            modelBuilder.Entity("SocialMediaManager.API.Models.TwitterDailyMetric", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FollowerCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RecordedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ReplyCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RetweetCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalLikes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalViews")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TweetCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TwitterAccountId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TwitterAccountId");

                    b.ToTable("TwitterDailyMetrics");
                });

            modelBuilder.Entity("SocialMediaManager.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SocialMediaManager.API.Models.DiscordAccount", b =>
                {
                    b.HasOne("SocialMediaManager.API.Models.User", "User")
                        .WithMany("DiscordAccounts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SocialMediaManager.API.Models.ScheduledPost", b =>
                {
                    b.HasOne("SocialMediaManager.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SocialMediaManager.API.Models.TelegramAccount", b =>
                {
                    b.HasOne("SocialMediaManager.API.Models.User", "User")
                        .WithMany("TelegramAccounts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SocialMediaManager.API.Models.TwitterAccount", b =>
                {
                    b.HasOne("SocialMediaManager.API.Models.User", "User")
                        .WithMany("TwitterAccounts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SocialMediaManager.API.Models.TwitterDailyMetric", b =>
                {
                    b.HasOne("SocialMediaManager.API.Models.TwitterAccount", "TwitterAccount")
                        .WithMany("DailyMetrics")
                        .HasForeignKey("TwitterAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TwitterAccount");
                });

            modelBuilder.Entity("SocialMediaManager.API.Models.User", b =>
                {
                    b.HasOne("SocialMediaManager.API.Models.User", "Parent")
                        .WithMany("Subaccounts")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("SocialMediaManager.API.Models.TwitterAccount", b =>
                {
                    b.Navigation("DailyMetrics");
                });

            modelBuilder.Entity("SocialMediaManager.API.Models.User", b =>
                {
                    b.Navigation("DiscordAccounts");

                    b.Navigation("Subaccounts");

                    b.Navigation("TelegramAccounts");

                    b.Navigation("TwitterAccounts");
                });
#pragma warning restore 612, 618
        }
    }
}
